[workspace]
members = ["bitwise","nonzero"]

[workspace.dependencies]
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.6.0", features = ["cuda"] }
half = "2.4.1"
cudarc = "0.11.4"
bindgen_cuda = "0.1.5"
criterion = "0.5.1"
rayon = "1.10.0"
